### ISSUE TITLE
YOLOv5版本更新了utils模块相关函数，导致不能运行！

### ISSUE THREAD

**Issue by 2197808908a** [KinkangLiu/Monocular_Distance_Detect#1]
Traceback (most recent call last): File "estimate_distance.py", line 19, in <module> from models.experimental import attempt_load File "C:\Users\Administrator\Desktop\AI\AI_Vision\Monocular_Distance_Detect-main\models\experimental.py", line 7, in <module> from models.common import Conv, DWConv File "C:\Users\Administrator\Desktop\AI\AI_Vision\Monocular_Distance_Detect-main\models\common.py", line 15, in <module> from utils.datasets import letterbox ModuleNotFoundError: No module named 'utils.datasets'

**Comment by avonyu** [comment]
直接在utils目录下的其他文件里搜索相关函数即可

**Comment by 2197808908a** [comment]
嗯，谢谢！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年10月12日(星期四) 晚上8:42
收件人: "KinkangLiu/Monocular_Distance_Detect";
抄送: "Author";
主题: Re: [KinkangLiu/Monocular_Distance_Detect] YOLOv5版本更新了utils模块相关函数，导致不能运行！ (#1)





 
直接在utils目录下的其他文件里搜索相关函数即可
 
&mdash;
